[package]
name = "ethnum"
version = "1.2.2"
authors = ["Nicholas Rodrigues Lordello <nlordell@gmail.com>"]
edition = "2021"
description = "256-bit integer implementation"
documentation = "https://docs.rs/ethnum"
readme = "README.md"
homepage = "https://github.com/nlordell/ethnum-rs"
repository = "https://github.com/nlordell/ethnum-rs"
license = "MIT OR Apache-2.0"
keywords = ["integer", "u256", "ethereum"]
categories = ["cryptography::cryptocurrencies", "mathematics", "no-std"]

[package.metadata.docs.rs]
features = ["serde"]

[workspace]
members = ["bench", "fuzz", "intrinsics"]

[features]
llvm-intrinsics = ["ethnum-intrinsics"]
scale = ["parity-scale-codec"]

[dependencies]
ethnum-intrinsics = { version = "1", path = "intrinsics", optional = true }
serde = { version = "1", default-features = false, optional = true }
rlp = { version = "0.5", optional = true }
parity-scale-codec = { version = "3", features = [
    "max-encoded-len",
], optional = true }
